
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
    ports:
      - "3000:3000"  # Reactアプリのポート
    volumes:
      - .:/app  # 開発環境ではローカルのソースをマウント
    env_file:
      - .env  # 共通の環境変数ファイル (.envにすべての環境変数を記述)
    entrypoint: ./entrypoint.sh   # entrypoint.shを使う

    # depends_on:
    #   - firebase
    
    healthcheck:
      test: ["CMD-SHELL", "curl -k -v http://localhost:3000 || exit 1"]
      interval: 90s
      timeout: 60s
      retries: 5
      start_period: 300s

    environment:
      VITE_NODE_ENV: ${VITE_NODE_ENV}  # 環境に応じた設定（開発・本番）

    working_dir: /app
    command: |
      chmod -R 777 /app/test-results /app/playwright-report

  nginx:
    image: nginx:latest
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/nginx/nginx.conf  # Nginx設定ファイルをマウント
      - ./server.cert.pem:/etc/ssl/certs/server.cert.pem  # PEM形式の証明書をマウント
      - ./server.key.pem:/etc/ssl/private/server.key.pem  # PEM形式の秘密鍵をマウント
    # depends_on:
    #   - app  # appが起動してからnginxが起動
    environment:
      VITE_NODE_ENV: ${VITE_NODE_ENV}  # 本番環境用のNginx設定（開発用にも使える）

  firebase:
    build:
      context: .  
      dockerfile: ./firebase/Dockerfile  
    env_file:
      - .env  # 共通の環境変数ファイル (.envにすべての環境変数を記述)
    environment:
      - VITE_GOOGLE_APPLICATION_CREDENTIALS="/firebase/serviceAccountKey.json"
      # - FIREBASE_TOKEN=${VITE_FIREBASE_TOKEN}
     
    ports:
      - "8080:8080"
      - "5001:5001"
      - "5000:5000"
      - "8090:8090"
      - "9199:9199"
      - "8091:8091"
      - "8085:8085"

    entrypoint: ["/bin/bash", "/firebase/entrypoint.sh"]
    command: firebase emulators:start --only firestore,functions,firestore,auth,storage # Firebaseエミュレーターを起動するコマンド
    volumes:
      - /Users/Tsp33786/Desktop/trial_html/MY_WEB_SIGHT/reminder/storage.rules
    # depends_on:
    #   - app  # appが起動してからfirebaseが起動

  playwright:
    build:
      context: .
      dockerfile: Dockerfile
    image: mcr.microsoft.com/playwright:v1.48.1-focal
    env_file:
      - .env  # 共通の環境変数ファイル (.envにすべての環境変数を記述)
    environment:
      VITE_REACT_APP_API_URL: ${VITE_REACT_APP_API_URL}
      VITE_REACT_APP_TEST_EMAIL: ${VITE_REACT_APP_TEST_EMAIL}
      VITE_REACT_APP_TEST_PASSWORD: ${VITE_REACT_APP_TEST_PASSWORD}
      DEBUG: pw:api  # デバッグログを有効化
      VITE_NODE_ENV: production
    volumes:
      - .:/app
      - ./server.key.pem:/app/server.key.pem
      - ./server.cert.pem:/app/server.cert.pem
    working_dir: /app

    depends_on:
      app:
        condition: service_healthy
    command: npx playwright test  

    # command: npx playwright test
