# HTTPS server block
server {
    listen 443 ssl;
    server_name localhost;

    ssl_certificate "/Users/Tsp33786/Desktop/trial html/MY_WEB_SIGHT/reminder/server.cert";
    ssl_certificate_key "/Users/Tsp33786/Desktop/trial html/MY_WEB_SIGHT/reminder/server.key";

    # Reactアプリへのプロキシ設定
    location / {
        proxy_pass http://localhost:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# HTTPからHTTPSへのリダイレクト
server {
    listen 80;
    server_name localhost;
    return 301 https://$host$request_uri;
}
