# # ci.yml
# on:
#   push:
#     branches:
#       - master
#   pull_request:
#     branches:
#       - master

# # playwright.yml
# on:
#   pull_request:
#     branches:
#       - master

# ci.yml
# on:
#   push:
#     branches:
#       - master
#     paths:
#       - 'src/**'        # ここで指定したディレクトリが変更されたときにのみ実行
#       - 'tests/**'
#   pull_request:
#     branches:
#       - master

