name: CI/CD Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Clean Docker system
        run: docker system prune -a -f
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Verify Docker Buildx Version
        run: docker buildx version

      - name: Create .env file
        run: |
          echo "VITE_HTTPS=${{ secrets.VITE_HTTPS }}" >> .env
          echo "VITE_REACT_APP_API_URL=${{ secrets.VITE_REACT_APP_API_URL }}" >> .env
          echo "DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}" >> .env
          echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" >> .env
          echo "VITE_FIREBASE_EMULATOR_HOST=${{ secrets.FIREBASE_EMULATOR_HOST }}" >> .env
          echo "VITE_FIREBASE_TOKEN=${{ secrets.FIREBASE_TOKEN }}" >> .env
          echo "VITE_GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" >> .env
          echo "VITE_REACT_APP_FIREBASE_API_KEY=${{ secrets.REACT_APP_FIREBASE_API_KEY }}" >> .env
          echo "VITE_REACT_APP_FIREBASE_APP_ID=${{ secrets.REACT_APP_FIREBASE_APP_ID }}" >> .env
          echo "VITE_REACT_APP_FIREBASE_AUTH_DOMAIN=${{ secrets.REACT_APP_FIREBASE_AUTH_DOMAIN }}" >> .env
          echo "VITE_REACT_APP_FIREBASE_PROJECT_ID=${{ secrets.REACT_APP_FIREBASE_PROJECT_ID }}" >> .env
          echo "VITE_REACT_APP_FIREBASE_STORAGE_BUCKET=${{ secrets.REACT_APP_FIREBASE_STORAGE_BUCKET }}" >> .env
          echo "VITE_REACT_APP_TEST_EMAIL=${{ secrets.VITE_REACT_APP_TEST_EMAIL }}" >> .env
          echo "VITE_REACT_APP_TEST_PASSWORD=${{ secrets.VITE_REACT_APP_TEST_PASSWORD }}" >> .env
          echo "VITE_NODE_ENV=${{ secrets.VITE_NODE_ENV }}" >> .env
          echo "VITE_HOST=${{ secrets.VITE_HOST }}" >> .env
          echo "VITE_NGROK_AUTH_TOKEN=${{ secrets.VITE_NGROK_AUTH_TOKEN }}" >> .env

          # 証明書ファイルの作成
          printf -- "${{ secrets.VITE_SERVER_CERT }}" > server.cert.pem
          printf -- "${{ secrets.VITE_SERVER_KEY }}" > server.key.pem

      - name: Debug .env file
        run: cat .env
        
      - name: Load Environment Variables
        run: |
          set -a
          source .env
          set +a

      - name: Download and install ngrok
        run: |
          curl -sL https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz -o ngrok.tgz
          tar -xvf ngrok.tgz -C /usr/local/bin
          chmod +x /usr/local/bin/ngrok

      - name: Verify ngrok installation
        run: ngrok version

      - name: Validate VITE_NGROK_AUTH_TOKEN
        run: |
          echo "Debugging VITE_NGROK_AUTH_TOKEN:"
          echo "VITE_NGROK_AUTH_TOKEN=$VITE_NGROK_AUTH_TOKEN"
      
      - name: Set up ngrok
        run: |
          ngrok config add-authtoken "${{ secrets.VITE_NGROK_AUTH_TOKEN }}"
        env:
          VITE_NGROK_AUTH_TOKEN: ${{ secrets.VITE_NGROK_AUTH_TOKEN }}

      - name: Start ngrok
        run: |
          docker-compose up -d ngrok
          # ngrok が準備できるまで待機（適切な時間に調整）
          sleep 10

      - name: Fetch Ngrok URL
        run: |
          NGROK_URL=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')
          echo "NGROK_URL=${NGROK_URL}" >> $GITHUB_ENV
    
      - name: Use Ngrok URL
        run: |
          echo "Ngrok URL is ${{ env.NGROK_URL }}"
        env:
          NGROK_URL: ${{ env.NGROK_URL }}

      - name: Debug current directory
        run: |
          pwd
          ls -la
          
      - name: Build Docker image (App)
        run: docker buildx build --build-arg VITE_NGROK_AUTH_TOKEN=${{ secrets.VITE_NGROK_AUTH_TOKEN }} -f ./Dockerfile -t app:latest --load --progress=plain .
        
      - name: Start ngrok container
        run: |
          docker run -d --name ngrok \
            -e VITE_NGROK_AUTH_TOKEN=$VITE_NGROK_AUTH_TOKEN \
            -p 4040:4040 \
            ngrok/ngrok http 3000

          sleep 10
      
      - name: Create Service Account Key
        run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > ./serviceAccountKey.json

      - name: Copy Service Account Key to Functions
        run: cp ./serviceAccountKey.json ./functions/serviceAccountKey.json

      - name: Copy Service Account Key to Firebase
        run: cp ./serviceAccountKey.json ./firebase/serviceAccountKey.json

      - name: Build Docker image (Compose)
        run: docker-compose build

      - name: Build Docker image (App)
        run: docker build -t app:latest .

      - name: Start Vite HTTPS Server
        run: npm run dev -- --https &

      - name: Debug app container
        run: docker-compose logs app

      - name: Log in to Docker Hub
        if: github.event_name == 'push'
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run ESLint with auto-fix
        run: npx eslint src/ --fix

  E2E-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Clear Playwright cache
        run: rm -rf /home/runner/.cache/ms-playwright
    
      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Install Playwright dependencies
        run: sudo apt-get install -y libx11-dev libxcomposite-dev libxrandr-dev libasound2-dev libatk-bridge2.0-dev libgtk-3-dev
    
      - name: Install Playwright Test
        run: npm install --save-dev @playwright/test
      
      - name: Install dependencies
        run: npm install 
      
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.11.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version
      
      - name: Install jq
        run: sudo apt-get install jq

      - name: Install latest ngrok
        run: |
          # 古いngrokの削除
          rm -f /usr/local/bin/ngrok
          rm -rf /home/runner/.ngrok
          # 最新バージョンのngrokを公式サイトからダウンロード
          curl -s https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip -o ngrok.zip
          unzip ngrok.zip
          # ngrokをインストール先ディレクトリに移動
          mkdir -p /home/runner/.ngrok
          mv ngrok /home/runner/.ngrok/ngrok
          rm ngrok.zip
          # ngrokをパスに追加
          echo "/home/runner/.ngrok" >> $GITHUB_PATH
          # パスが正しいことを確認
          echo $PATH
          # インストールされたバージョンを確認
          /home/runner/.ngrok/ngrok version
      
      # - name: Install ngrok
      #   run: |
      #     curl -s https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip -o ngrok.zip
      #     unzip ngrok.zip
      #     mv ngrok /usr/local/bin
      #     rm ngrok.zip
  
      - name: Verify ngrok installation
        run: ngrok version

      - name: Create .env file and keys
        run: |
          echo "VITE_HTTPS=${{ secrets.VITE_HTTPS }}" >> .env
          echo "VITE_REACT_APP_API_URL=${{ secrets.VITE_REACT_APP_API_URL }}" >> .env
          echo "VITE_REACT_APP_TEST_EMAIL=${{ secrets.VITE_REACT_APP_TEST_EMAIL }}" >> .env
          echo "VITE_REACT_APP_TEST_PASSWORD=${{ secrets.VITE_REACT_APP_TEST_PASSWORD }}" >> .env
          echo "VITE_NODE_ENV=${{ secrets.VITE_NODE_ENV }}" >> .env
          echo "VITE_HOST=${{ secrets.VITE_HOST }}" >> .env
          echo "VITE_NGROK_AUTH_TOKEN=${{ secrets.VITE_NGROK_AUTH_TOKEN }}" >> .env

            # 証明書ファイルの作成
          printf -- "${{ secrets.VITE_SERVER_CERT }}" > server.cert.pem
          printf -- "${{ secrets.VITE_SERVER_KEY }}" > server.key.pem
      
      - name: Start ngrok and fetch URL
        run: |
          ngrok authtoken $VITE_NGROK_AUTH_TOKEN
          ngrok http 3000 > ngrok.log 2>&1 &
          sleep 5
          NGROK_URL=$(curl --silent http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url')
          if [ -n "$NGROK_URL" ]; then
            echo "Ngrok URL fetched: $NGROK_URL"
            echo "NGROK_URL=${NGROK_URL}" >> $GITHUB_ENV
          else
            echo "Error: Failed to fetch ngrok URL"
            cat ngrok.log
            exit 1
          fi
        env:
          VITE_NGROK_AUTH_TOKEN: ${{ secrets.VITE_NGROK_AUTH_TOKEN }}
  
      - name: Use Ngrok URL
        run: |
          echo "Ngrok URL is ${{ env.NGROK_URL }}"
        env:
          NGROK_URL: ${{ env.NGROK_URL }}

      - name: Debug .env file contents
        run: cat .env
        
      - name: Set up ngrok authtoken
        run: ngrok authtoken ${{ secrets.VITE_NGROK_AUTH_TOKEN }}

      - name: test ngrok authtoken
        run: |
          echo "VITE_NGROK_AUTH_TOKEN=${{ secrets.VITE_NGROK_AUTH_TOKEN }}"
          ngrok authtoken ${{ secrets.VITE_NGROK_AUTH_TOKEN }}

      - name: Entrypoint
        run: ./entrypoint.sh
             chmod +x ./entrypoint.sh

      - name: Build Docker image (App)
        run: docker build -t app:latest .

    
      - name: Run Playwright tests
        run: |
          NGROK_URL=${{ env.NGROK_URL }}  # 環境変数として指定
          export NGROK_URL=$NGROK_URL
        env:
          VITE_HTTPS: ${{ secrets.VITE_HTTPS }}
          VITE_REACT_APP_API_URL: ${{ secrets.VITE_REACT_APP_API_URL }}
          VITE_REACT_APP_TEST_EMAIL: ${{ secrets.VITE_REACT_APP_TEST_EMAIL }}
          VITE_REACT_APP_TEST_PASSWORD: ${{ secrets.VITE_REACT_APP_TEST_PASSWORD }}
          VITE_NODE_ENV: ${{ secrets.VITE_NODE_ENV }}
          VITE_HOST: ${{ secrets.VITE_HOST }}
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
          NGROK_URL: ${{ env.NGROK_URL }}  # 必要な環境変数を指定
       
      - name: Debug current directory
        run: |
          pwd
          ls -la
      
      - name: Buildx build Docker image (App)
        run: docker buildx build --build-arg VITE_NGROK_AUTH_TOKEN=${{ secrets.VITE_NGROK_AUTH_TOKEN}} -f ./Dockerfile -t app:latest --load --progress=plain .

    
       # ngrok コンテナを起動
      - name: Start ngrok container
        run: |
          docker run -d --name ngrok \
            -e VITE_NGROK_AUTH_TOKEN=$VITE_NGROK_AUTH_TOKEN \
            -p 4041:4040 \
            ngrok/ngrok http 3000
       
          sleep 10

      # アプリの Docker イメージをビルド
      - name: Build Docker image (App)
        run: docker build -t app:latest .

      # アプリコンテナを起動
      - name: Run app container with ngrok auth and URL
        run: |
          docker run -d --name app-container \
            -e VITE_NGROK_AUTH_TOKEN=${{ secrets.VITE_NGROK_AUTH_TOKEN }} \
            -e NGROK_URL=${{ env.NGROK_URL }} \
            -p 3002:3000 \
            app:latest

      - name: Build and Start App
        run: |
          docker-compose down --volumes
          docker system prune -f
          docker-compose build
          docker-compose up -d

      - name: Show Logs
        run: docker-compose logs app

      - name: Set permissions for test-results directory
        run: |
          sudo chmod 777 server.key.pem
          sudo chmod 777 server.cert.pem
          sudo chown root:root server.key.pem
          sudo chown root:root server.cert.pem
          sudo mkdir -p $GITHUB_WORKSPACE/playwright-test-results
          sudo chmod -R 777 $GITHUB_WORKSPACE/playwright-test-results 
          sudo mkdir -p $GITHUB_WORKSPACE/test-results
          sudo chmod -R 777 $GITHUB_WORKSPACE/test-results
          mkdir -p ./test-results

      - name: Fix permissions
        run: |
          sudo rm -rf ./test-results
          mkdir -p ./test-results
          sudo chmod -R 777 ./test-results
          sudo chown -R $USER:$USER ./test-results
          
      - name: Check certificate files
        run: |
          ls -l server.key.pem
          ls -l server.cert.pem
      
      - name: Run E2E Tests
        run: |
          docker run -e NGROK_URL=${{ env.NGROK_URL }} \
            mcr.microsoft.com/playwright:v1.49.0-jammy  \
            npx playwright test ./tests
      
      - name: Run Playwright Tests
        run: |
          npx playwright test --reporter=html
      
      # Playwright テストログ（失敗した場合のみ）
      - name: Playwright Test Logs
        if: failure()
        run: cat playwright-report/output.log

      # テスト終了後にコンテナをダウン
      - name: Teardown
        run: docker-compose down
      
  deploy:
    runs-on: ubuntu-latest
    needs:
      - lint
      - E2E-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Set up Firebase credentials
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > /tmp/keyfile.json
          export GOOGLE_APPLICATION_CREDENTIALS="/tmp/keyfile.json"

      - name: Deploy to Firebase
        run: |
          firebase deploy --project "${{ secrets.FIREBASE_PROJECT_ID }}" --token "${{ secrets.FIREBASE_TOKEN }}"













