name: Playwright E2E Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # 30分まで延長

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # - name: Clean test results directory
      #   run: rm -rf test-results

      # - name: Set up test results directory
      #   run: |
      #     mkdir -p test-results
      #     chmod -R 777 test-results
    
      # - name: Set up report directory with permissions
      #   run: |
      #     mkdir -p playwright-report
      #     chmod -R 777 playwright-report

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.11.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      - name: Create .env file
        run: |
          echo "VITE_REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}" >> .env
          echo "VITE_REACT_APP_TEST_EMAIL=${{ secrets.REACT_APP_TEST_EMAIL }}" >> .env
          echo "VITE_REACT_APP_TEST_PASSWORD=${{ secrets.REACT_APP_TEST_PASSWORD }}" >> .env
          echo "VITE_REACT_APP_TEST2_EMAIL=${{ secrets.REACT_APP_TEST2_EMAIL }}" >> .env
          echo "VITE_REACT_APP_TEST2_PASSWORD=${{ secrets.REACT_APP_TEST2_PASSWORD }}" >> .env

      - name: Prepare Docker Compose
        run: docker-compose down

      - name: Set up Docker Compose
        run: docker-compose build
      
      - name: Run app and tests
        run: docker-compose up --abort-on-container-exit --build

      # - name: Start app using Docker Compose
      #   run: docker-compose up --build -d
        
      # - name: Wait for app to be ready
      #   run: |
      #     for i in {1..20}; do
      #       if curl -k -s https://localhost:3000 > /dev/null; then
      #         echo "App is ready!"
      #         break
      #       fi
      #       echo "Waiting for app to be ready..."
      #       sleep 5
      #     done

      - name: Run E2E Tests
        run: npx playwright test
        if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }} # CI/CDのみに制限
        env:
          VITE_REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
          VITE_REACT_APP_TEST_EMAIL: ${{ secrets.REACT_APP_TEST_EMAIL }}
          VITE_REACT_APP_TEST2_EMAIL: ${{ secrets.REACT_APP_TEST2_EMAIL }}
          VITE_REACT_APP_TEST_PASSWORD: ${{ secrets.REACT_APP_TEST_PASSWORD }}
          VITE_REACT_APP_TEST2_PASSWORD: ${{ secrets.REACT_APP_TEST2_PASSWORD }}
      
      - name: Playwright Test Logs
        if: failure()
        run: cat playwright-report/output.log
      
      - name: Teardown
        run: docker-compose down
