name: Playwright E2E Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-start-app:
    runs-on: ubuntu-latest
    timeout-minutes: 30  

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install 
      
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.11.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      - name: Create .env file and keys
        run: |
          echo "VITE_HTTPS=${{ secrets.VITE_HTTPS }}" >> .env
          echo "VITE_REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}" >> .env
          echo "VITE_REACT_APP_TEST_EMAIL=${{ secrets.REACT_APP_TEST_EMAIL }}" >> .env
          echo "VITE_REACT_APP_TEST_PASSWORD=${{ secrets.REACT_APP_TEST_PASSWORD }}" >> .env
          echo "VITE_NODE_ENV=${{ secrets.NODE_ENV }}" >> .env
          echo "${{ secrets.SERVER_CERT }}" > server.cert.pem
          echo "${{ secrets.SERVER_KEY }}" > server.key.pem
          echo "VITE_HOST ${{ secrets.VITE_HOST }}" >> .env

      - name: Build and Start App
        run: |
          docker-compose down
          docker-compose build
          docker-compose up -d
        env:
          VITE_HTTPS: ${{ secrets.VITE_HTTPS }}
          VITE_REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
          VITE_REACT_APP_TEST_EMAIL: ${{ secrets.REACT_APP_TEST_EMAIL }}
          VITE_REACT_APP_TEST_PASSWORD: ${{ secrets.REACT_APP_TEST_PASSWORD }}
          VITE_NODE_ENV: ${{ secrets.NODE_ENV }}
          VITE_SERVER_CERT: ${{ secrets.SERVER_CERT }}
          VITE_SERVER_KEY: ${{ secrets.SERVER_KEY }}
          VITE_HOST: ${{ secrets.VITE_HOST }}

  e2e-tests:
    needs: build-and-start-app  # 依存関係を追加
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Install Playwright Test
        run: npm install --save-dev @playwright/test

      # - name: Wait for server to be ready
      #   run: npx wait-on https://localhost:3000

      - name: Run E2E Tests
        run: npx playwright test
        env:
          VITE_HTTPS: ${{ secrets.VITE_HTTPS }}
          VITE_REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
          VITE_REACT_APP_TEST_EMAIL: ${{ secrets.REACT_APP_TEST_EMAIL }}
          VITE_REACT_APP_TEST_PASSWORD: ${{ secrets.REACT_APP_TEST_PASSWORD }}
          VITE_NODE_ENV: ${{ secrets.NODE_ENV }}
          VITE_SERVER_CERT: ${{ secrets.SERVER_CERT }}
          VITE_SERVER_KEY: ${{ secrets.SERVER_KEY }}
          VITE_HOST: ${{ secrets.VITE_HOST }}

      - name: Create .env file and keys
        run: |
          echo "VITE_HTTPS=${{ secrets.VITE_HTTPS }}" >> .env
          echo "VITE_REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}" >> .env
          echo "VITE_REACT_APP_TEST_EMAIL=${{ secrets.REACT_APP_TEST_EMAIL }}" >> .env
          echo "VITE_REACT_APP_TEST_PASSWORD=${{ secrets.REACT_APP_TEST_PASSWORD }}" >> .env
          echo "VITE_NODE_ENV=${{ secrets.NODE_ENV }}" >> .env
          echo "${{ secrets.SERVER_CERT }}" > server.cert.pem
          echo "${{ secrets.SERVER_KEY }}" > server.key.pem
          echo "${{ secrets.VITE_HOST }}" >> .env

      - name: Playwright Test Logs
        if: failure()
        run: cat playwright-report/output.log

      - name: Teardown
        run: docker-compose down
