name: Playwright E2E Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      
      # apt-getを使ってDocker Composeをインストール
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose-plugin
          docker compose version

      - name: Create .env file
        run: |
          echo "REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}" >> .env
          echo "REACT_APP_TEST_EMAIL=${{ secrets.REACT_APP_TEST_EMAIL }}" >> .env
          echo "REACT_APP_TEST_PASSWORD=${{ secrets.REACT_APP_TEST_PASSWORD }}" >> .env
          echo "REACT_APP_TEST2_EMAIL=${{ secrets.REACT_APP_TEST2_EMAIL }}" >> .env
          echo "REACT_APP_TEST2_PASSWORD=${{ secrets.REACT_APP_TEST2_PASSWORD }}" >> .env

      - name: Start app using Docker Compose
        run: docker-compose up -d

      - name: Wait for app to be ready
        run: |
          for i in {1..10}; do
            if curl -s -f http://app:3000; then
              echo "App is ready!"
              break
            fi
            echo "Waiting for app to be ready..."
            sleep 10
          done

      - name: Run E2E Tests
        run: |
          docker-compose up -d
          docker run --rm -e REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }} \
            -e REACT_APP_TEST_EMAIL=${{ secrets.REACT_APP_TEST_EMAIL }} \
            -e REACT_APP_TEST_PASSWORD=${{ secrets.REACT_APP_TEST_PASSWORD }} \
            ${{ secrets.DOCKER_USERNAME }}/app:app2 npm run test:e2e --fix
        env:
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
          REACT_APP_TEST_EMAIL: ${{ secrets.REACT_APP_TEST_EMAIL }}
          REACT_APP_TEST2_EMAIL: ${{ secrets.REACT_APP_TEST2_EMAIL }}
          REACT_APP_TEST_PASSWORD: ${{ secrets.REACT_APP_TEST_PASSWORD }}
          REACT_APP_TEST2_PASSWORD: ${{ secrets.REACT_APP_TEST2_PASSWORD }}
